env:
  es2021: true
  browser: true
  commonjs: true
  jest: true

extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended"]

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins: ["react", "@typescript-eslint"]

settings:
  react:
    version: detect

rules:
  no-console: error
  import/prefer-default-export: "off"
  react/jsx-no-useless-fragment: "warn"

root: true
